services:
  core:
    image: yuzutech/kroki
    environment:
      - KROKI_MAX_URI_LENGTH=8192
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
    ports:
      - "${HTTP_PORT:-8000}:8000"
    networks:
      - kroki_network

  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
    networks:
      - kroki_network

  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"
    networks:
      - kroki_network

  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"
    networks:
      - kroki_network

  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    expose:
      - "8005"
    networks:
      - kroki_network

  demosite:
    image: kroki-demosite:latest
    expose:
      - "${DEMOSITE_CONTAINER_PORT:-8006}"
    environment:
      - PORT=${DEMOSITE_CONTAINER_PORT:-8006}
    env_file:
      - .env
    networks:
      - kroki_network

  nginx:
    image: nginx
    depends_on:
      - core
    ports:
      - "${HTTPS_PORT:-8443}:8443"
    volumes:
      - ./nginx-certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - kroki_network
    networks:
      - kroki_network

networks:
  kroki_network:
    driver: bridge
