version: "3.3" 

services:
  core:
    image: yuzutech/kroki
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
    ports:
      - "8000:8000"
    networks:
      - kroki_network

  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
    networks:
      - kroki_network

  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"
    networks:
      - kroki_network

  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"
    networks:
      - kroki_network

  # experimental!
  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    expose:
      - "8005"
    networks:
      - kroki_network

  demosite:
    image: kroki-demosite:latest
    expose:
      - "8006"
    environment:
      - PORT=8006
      - AI_ENABLED=${AI_ENABLED:-true}
      - AI_ENDPOINT=${AI_ENDPOINT:-https://api.openai.com/v1/chat/completions}
      - AI_MODEL=${AI_MODEL:-gpt-3.5-turbo}
      - AI_TIMEOUT=${AI_TIMEOUT:-30}
      - AI_API_KEY=${AI_API_KEY:-}
    env_file:
      - ./demoSite/.env
    networks:
      - kroki_network

  nginx:
    image: nginx
    container_name: nginx-kroki
    depends_on:
      - core
    ports:
      - "8443:8443"
    volumes:
      - ./nginx-certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - kroki_network

networks:
  kroki_network:
    driver: bridge
