name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './setup-kroki-server.sh'
          
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Test setup script
        run: |
          chmod +x ./setup-kroki-server.sh
          ./setup-kroki-server.sh start
          sleep 30
          curl -k -s -o /dev/null -w "%{http_code}" https://localhost:8443 | grep -q "200"
          ./setup-kroki-server.sh stop
  demo-site-container:
    name: Build Demo Site Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/kroki-server-demosite
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short
            latest
            
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./demoSite
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Add caching to improve build times
          cache-from: type=gha
          cache-to: type=gha,mode=max