version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "docker"
    directory: "/demoSite"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"