name: Build Docker Images

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

# Add explicit permissions for packages
permissions:
  contents: read
  packages: write

jobs:
  build-demo-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/kroki-server
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short
            latest
            
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./demoSite
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Add caching to improve build times
          cache-from: type=gha
          cache-to: type=gha,mode=max